### ISSUE TITLE
how can

### ISSUE THREAD

**Issue by nick814** [Molkobain/itop-fontawesome5-pack#1]
hi
i install this extensions in my itop 2.5,but there is nothing change .
and i see you readme.md  but i can't find the file /itop_design/module_designs  my itop don't has this folder ,what can i do

**Comment by Molkobain** [comment]
Hi Nick,

This extension **allows** you to use new icons, it doesn't change anything if you just install it.

Changing brick icons in the end-users portal is made through datamodel (XML) customization, check the documentation [here](https://www.itophub.io/wiki/page?id=2_5_0%3Acustomization%3Astart) and [here](https://www.itophub.io/wiki/page?id=2_5_0%3Acustomization%3Aportal_xml).

**Comment by Molkobain** [comment]
*/itop_design/module_designs* isn't a file, it's the XPath in the datamodel XML. So if you want to change it, you have to make it through your own itop extension.
